name: Secret Scanning with Gitleaks

on:
  push:
    branches:
      - "**" # ALL branches
  pull_request:
    branches:
      - "**" # ALL branches

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          apt update
          apt install gitleaks

      - name: Run Gitleaks Scan
        run: |
          gitleaks detect --redact --verbose
          gitleaks detect --redact --report=gitleaks-report.json

      - name: Handle Failure
        if: failure()
        run: |
          echo "❌ Secrets detected! Fix them before merging."
          exit 1
